export const offlineOrderDishesSelectors = {
  customerInfoPopup: 'customer-info-popup',
  customerNameInput: 'customer-name',
  customerPhoneInput: 'customer-phone',
  customerSubmitButton: 'customer-submit',
  itemDiscountButton: 'item-discount-10',
  itemPrice: 'order-item-price',
  itemPriceInput: 'item-price-input',
  itemPriceSubmitButton: 'item-price-submit',
  itemQuantityButton: 'order-item-quantity-button',
  itemQuantityInput: 'order-item-quantity',
  itemQuantitySubmitButton: 'order-item-quantity-submit',
  itemTax: 'order-tax',
  managerPasswordInput: 'manager-password',
  managerPasswordSubmitButton: 'manager-password-submit',
  openFoodButton: 'order-open-food',
  openFoodNameInput: 'open-food-name',
  openFoodNoTaxButton: 'open-food-no-tax',
  openFoodPriceInput: 'open-food-price',
  reduceItemButton: 'order-reduce-item',
  settleButton: 'order-settle',
  voidItemButton: 'order-void-item',
} as const;
