export const liveOrderDishesSelectors = {
  customerInfoPopup: '#customer-dialog',
  customerNameInput: '#customer-dialog:visible #customer-name',
  customerPhoneInput: '#customer-dialog:visible #customer-phone',
  customerSubmitButton: '#customer-dialog:visible #customer-submit',
  itemDiscountTrigger: '#chgPrcicon',
  itemPrice: '.itemttPrc',
  itemPriceInput: '#smpiptipt',
  itemPriceSubmitButton: '#smpiptgo',
  itemPriceClearButton: '#kbrclc',
  itemQuantityButton: '#chgNumicon',
  itemQuantityInput: '#number-input',
  itemQuantitySubmitButton: '#number-input-submit',
  itemTaxButton: '#chgTaxicon',
  itemTaxExemptButton: '#voidTaxTrue',
  itemTax: '#ododtt_tx_price',
  globalOptionAddButton: '//div[contains(@id,"optMnActBt")]/div[text()="Add"]',
  globalOptionArea: '#glbOptBx, #optMainBx',
  globalOptionCountButton: '#chgNumopt',
  globalOptionCountInput: '#number-input',
  globalOptionCountSubmitButton: '#number-input-submit',
  globalOptionNoButton: '//div[contains(@id,"optMnActBt")]/div[text()="No"]',
  globalOptionPricedChoice: '//div[contains(@id,"optMnOpt")]//p[contains(text(),"$")]',
  globalOptionReduceButton: '#reduce1opticon',
  comboConfirmButton: '#comboPreviewConfirmBtn',
  comboDetailChoice: '.SqlBtBoxBody > div',
  comboOptionButton: '.main-option .dishH_5',
  comboOptionCount: '.itemOptLogo',
  comboOptionReduceButton: '#reduce1opticon',
  comboSection: '[id*="complexComboSectionStep"]',
  comboSectionDescription: '#comboStepDescriptionBx',
  comboSubItemButton: '[id*="complexComboItemBtn"]',
  discountClearAllButton: '#dcclearall',
  discountDoneButton: '#disOk',
  discountKeyButtonPrefix: '#mykbfl_',
  discountPanel: '#subitemlist',
  discountPercentButton: '#perBtn_true',
  discountSelectedClearButton: '#clearSelected',
  discountRows: '#subitemlist [id*="dsitem_"]',
  orderDiscountAmount: '#ododDiscount',
  orderSubtotal: '#ododttst',
  managerPasswordInput: '#pwd-input',
  managerPasswordDialog: '#pwd-input-dialog:visible',
  managerPasswordDigitButton: '#pwd-input-dialog:visible .pwd-input-item[data-num="{digit}"]',
  managerPasswordSubmitButton: '#pwd-input-submit',
  orderHeaderBox: '#odinfooutbx',
  orderInfoButton: '#chgcstmrInfoicon',
  orderSaveButton: '#odSavetxt',
  menuGroupOption: '.floatSqlBt, [id*="SBtBx"] > div',
  menuGroupSwitchButton: '#oGrptxt',
  pickupNameInput: '#dlvInfoNm',
  pickupOrderButton: '#dlvpOdbx',
  searchClearButton: '#deliptsearchbx',
  searchInput: '#searchiptedit',
  searchResult: '#itemdsply > div > div:first-child > div > div',
  searchResultItem: '#itemdsply > div > div > div > div',
  openFoodButton: '#openFoodBx',
  openFoodHideKeyboardButton: '#kbrhide',
  openFoodNameInput: '#open-food-name',
  openFoodPriceInput: '#open-food-price',
  openFoodSubmitButton: '#open-food-submit',
  openFoodTaxButton: 'div[id*="tax_"]',
  optionButton: '#oddishoptbxlvl1 .dishes-option-btn',
  orderedItemName: '[class*="itemName"][class$="txt"]',
  orderedItemRow: '#oodbtbx [id*="itemdsh"]:has([class*="itemName"][class$="txt"])',
  settleBackupCardButton: '//div[normalize-space()="Backup"]',
  settleAllCashButton: '#pplnumbx > div:first-child',
  settleCardNumberIdInput: '#vpnoipt',
  settleCardFirstNameInput: '#fnameipt',
  settleCardResult: 'div[id*="vponecdsmy"]',
  settleCardSearchButton: '#vpsch',
  settleCardSetButton: '#vpgo',
  settleCashMethodButton: '#cashBT',
  settleGiftCardButton: '#gftBT',
  settleLoyaltyCardButton: '#vipBT',
  settleButton: '#odPay',
  settleEvenPayButton: '#pplsplit',
  settleEvenPayConfirmButton: '#dsfl',
  settleEvenPayGuestInput: '#numOfGst',
  settleStoredCardBalanceButton: '#usemoney',
  settlePayButton: '#pplcgpybt',
  settlePayAndPrintButton: '#pplcgppbt',
  settlePayAmountClearButton: '#pplbillclr',
  settleSelfCardButton: '#pplpacnt_1',
  settleToast: '#myalert',
  settleTipButton: '#ppltpbt',
  settleTipInput: '#tips-input, #smpiptipt',
  settleTipSubmitButton: '#tips-submit, #smpiptgo',
  settleUnpaidAmount: '#pplmnyiptTxt',
  subOptionButton: '#oddishoptbxlvl2 .dishes-option-btn',
  tenPercentDiscountButton: '//div[text()="10% off"]/parent::div',
  voidItemButton: '#odAvoid',
  voidItemButtonLater: '#rmvItemicon',
} as const;
